-- KUNDE
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900100,'Clerk','Simon');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900101,'Dyson','Smith');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900102,'Klingler','Walter');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900103,'Ruetz','Karl');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900104,'Jons','John');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900105,'Kurz','Harald');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900106,'Wagner','Ferdinand');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900107,'Habsburg','Otto');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900108,'Luise','Maria');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900109,'Felipe','Ingrid');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900110,'Traxler','Denis');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900111,'Hitzinger','Bernhard');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900112,'Straubel','Josef');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900113,'Wimmer','Arnold');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900114,'Schatz','Christiane');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900115,'Pop','Manuel');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900116,'Hirsch','Manfred');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900117,'Jäger','Thomas');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900118,'Nuener','Rudolf');
INSERT INTO ONLINEBANKING.OBKunde (ID,DATNEU,KUNDNR,NACHNAME,VORNAME) VALUES (UUID(),'2020-01-23',900119,'Stier','Wilhelm');

-- KONTO
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900100;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900100;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900100;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900101;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900101;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900101;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900102;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900102;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900102;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900103;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900103;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900103;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900104;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900104;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900104;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900105;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900105;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900105;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900106;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900106;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900106;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900107;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900107;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900107;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900108;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900108;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900108;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900109;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900109;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900109;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900110;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900110;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900110;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900111;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900111;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900111;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900112;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900112;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900112;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900113;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900113;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900113;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900114;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900114;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900114;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900115;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900115;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900115;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900116;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900116;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900116;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900117;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900117;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900117;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900118;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900118;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900118;

INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'GIRO' AS KONTOTYP, '2020-02-01' AS DATNEU, 'Gehaltskonto' AS DISPNAME, CONCAT(KU.KUNDNR,'200') AS KONTONR, '4000' AS SALDO,KU.ID, '5000' AS RAHMEN, '0.3' AS ZINSSATZHABEN, '12' AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900119;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch' AS DISPNAME, CONCAT(KU.KUNDNR,'300') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900119;
INSERT INTO ONLINEBANKING.OBKonto (ID, KontoTyp, DATNEU, DISPNAME, KONTONR, SALDO, KUNDE, RAHMEN, ZINSSATZHABEN,ZINSSATZSOLL) SELECT UUID() AS ID, 'SPAR' AS KONTOTYP, '2020-02-05' AS DATNEU, 'Sparbuch für mein Hobby' AS DISPNAME, CONCAT(KU.KUNDNR,'400') AS KONTONR, '0' AS SALDO,KU.ID, NULL AS RAHMEN, '1.5' AS ZINSSATZHABEN, NULL AS ZINSSATZSOLL
FROM ONLINEBANKING.OBKunde AS KU WHERE KU.KUNDNR = 900119;
